language: node_js
node_js:
  - "stable"
script: "npm run coveralls"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

script:
  - "npm run client-test"
  - "npm run server-test"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
